spring.application.name=coderunner
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/coderunner_db
spring.datasource.username=root
spring.datasource.password=Pooja@star3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true